//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appointment.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserView
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string phone_number { get; set; }
        public string email_address { get; set; }
        public int role_id { get; set; }
        public string description { get; set; }
    }
}
